CREATE TABLE public.device_latest_data (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id uuid NOT NULL UNIQUE REFERENCES public.devices(id) ON DELETE CASCADE,
    provider text NOT NULL,
    collected_at timestamptz,
    device_status text,
    pv_power numeric,
    ac_power numeric,
    grid_power numeric,
    battery_power numeric,
    battery_soc numeric,
    pv1_voltage numeric,
    pv1_current numeric,
    pv1_power numeric,
    pv2_voltage numeric,
    pv2_current numeric,
    pv2_power numeric,
    frequency numeric,
    inverter_temperature numeric,
    bus_voltage numeric,
    today_energy numeric,
    total_energy numeric,
    raw_data jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
